local util = require("prometheus.util");
local chararray = util.chararray;

local varNames = {
    -- ORIGINAL TOXIC NAMES (Roasting OLD/DEAD obfuscators)
    "PSUdead",
    "IronBrewRust",
    "OldMoonSec",
    "SkillIssue",
    "SkidDetected",
    "NiceTrieKid",
    "TouchGrass",
    "MomsCalling",
    "GoOutside",
    "StillHere",
    "justGiveUp",
    "WastingTime",
    "FailedCrack",
    "Deobfailed",
    "NahBrogetout",
    "CopeMald",
    "RatioPlusL",
    
    -- MORE TOXIC MEME NAMES
    "YouTriedLMAO",
    "StackOverflowed",
    "PasteFromYT",
    "V3rmiGotNuked",
    "LuraphCantAfford",
    "FreeObfuscator",
    "ForkPrometheus",
    "CopiedFromGithub",
    "DownBadCoding",
    "NoMaidens",
    "GetRekt",
    "MalwareDetected",
    "SusAmogus",
    "DeleteSystem32",
    "DownloadMoreRAM",
    "TaskFailed",
    "ErrorSuccess",
    "NullPointer",
    "SegFault",
    "BufferOverrun",
    "MemoryLeak",
    "InfiniteLoop",
    "DivideByZero",
    "IndexOutOfBounds",
    "FileNotFound",
    "AccessDenied",
    "ConnectionRefused",
    "TimeoutError",
    "BadRequest",
    "Unauthorized",
    "Forbidden",
    "NotFound",
    "ServerError",
    "CoffeeRequired",
    "BrainNotFound",
    "LogicError",
    "SyntaxError",
    "UnexpectedEOF",
    "MissingDependency",
    "DeprecatedFunc",
    "ObsoleteCode",
    "LegacySupport",
    "TechnicalDebt",
    "CodeSmells",
    "SpaghettiCode",
    "HackyWorkaround",
    "TODOFixLater",
    "ThisShouldntWork",
    "IDontKnowWhy",
    "ItWorksOnMyMachine",
    "MagicNumber",
    "HardCodedValue",
    "GlobalVariable",
    "GodObject",
    "CircularDependency",
    "DeepNesting",
    "LongMethod",
    "LazyLoading",
    "OverEngineered",
    "PrematureOptimization",
    "EdgeCaseIgnored",
    "UndocumentedFeature",
    "IntentionalBug",
    "WontFix",
    "WorksAsIntended",
    "ByDesign",
    "UserError",
    "LayerEightProblem",
    "WetwareFailure",
    "OrganicBug",
    "HumanException",
    "CaffeineLow",
    "SleepDeprived",
    "DeadlineApproaching",
    "CrunchMode",
    "ProductionPanic",
    "HotfixFriday",
    "EmergencyPatch",
    "RollbackRequired",
    "BackupNotFound",
    "DisasterRecovery",
    "SecurityHole",
    "VulnerabilityIgnored",
    "PatchLater",
    "UpdateRequired",
    "UnsupportedVersion",
    "BetaQuality",
    "AlphaRelease",
    "ProofOfConcept",
    "ExperimentalFeature",
    "UntestedCode",
    "QASkipped",
    "TestsNotWritten",
    "NoDocumentation",
    "ReadmeEmpty",
    "CommentsRemoved",
    "SelfDocumenting",
    "CleverSolution",
    "QuickAndDirty",
    "FastAndBroken",
    "ShipItNow",
    "BreakThings",
    "YOLOCommit",
    "PushToProduction",
    "HopeItWorks",
    "PrayAndDeploy",
    "TrustMeBro",
    "FamousLastWords",
    "WhatCouldGoWrong",
    "HoldMyBeer",
    "WatchThis",
    "ScriptKiddie",
    "FakeHacker",
    "PremiumPastebin",
    "FreeCodeCamp",
    "StackOverflowCopy",
    "GitHubClone",
    "NPMLeftPad",
    "CargoRust",
    "VimMaster",
    "EmacsForever",
    "VSCodePleb",
    "NotepadPlusPlus",
    "PrintfDebugger",
    "ConsoleLogWarrior",
    
    -- FAKE LUA KEYWORDS/FUNCTIONS
    "loadstring",
    "getfenv",
    "setfenv",
    "rawget",
    "rawset",
    "getmetatable",
    "setmetatable",
    "pcall",
    "xpcall",
    "tonumber",
    "tostring",
    "typeof",
    "next",
    "pairs",
    "ipairs",
    "select",
    "unpack",
    "newproxy",
    "coroutine",
    "debug",
    "string",
    "table",
    "math",
    "require",
    "module",
    "package",
    "assert",
    "collectgarbage",
    "dofile",
    "error",
    "gcinfo",
    "load",
    "rawequal",
    
    -- LONG RANDOM STRINGS (CLEANED)
    "KSSJSJSNSISEJNISNJEJEJKSOSMKDNWKDN",
    "XKJDNEMSJDIEKSOPWENJDIEKDMSKDIE",
    "PLMKOWNSJDIEQWERBNASDDCVFZXCVBN",
    "ZXCVBNQWERTYASDFGHHJKLZXCVBNMA",
    "TYUIOPGHJKLZXCVBNMQAZWSXEDCRFV",
    "QAZWSXEDCRFVTGBYHNUJMIKOLPMJNH",
    "UJMIKOLPMJNHYGBVFTCDEXSWZAQXCD",
    "CDEXSWZAQXCDERFVBGTHNMJUYIKOLO",
    "THNMJUYIKOLOPMNJBHVGYCFTXDRZSE",
    "VGYCFTXDRZSEAWQZSXEDCRFTVGYBHU",
    "PLOKIJUNHBGYVFTCRDZEXSWAQWZSXED",
    "HJKLZXCVBNMASDFGHJTYUIOPGHJKLZ",
    "MNBVCXLKJHGFDSAQWERTYJUIOPLKJHG",
    "ERFVBGTHNMJUYIKOLOPMNJBHVGYCFT",
    "AWQZSXEDCRFTVGYBHUNJMIKOLPMKOI",
    
    -- SUPER LONG STRINGS (CLEANED)
    "KSSJSJSNSISEJNISNJEJEJKSOSMKDNWKDNSKMWKDNPLMKOIUJNHBGYVFTCRDZEXSW",
    "XKJDNEMSJDIEKSOPWENJDIEKDMSKDIEPLOKIJUNHBGYVFTCRDZEXSWAQWZSXED",
    "PLMKOWNSJDIEQWERBNASDDCVFZXCVBNQWERTYASDFGHZXCVBNMNBVCXLKJHGF",
    "ZXCVBNQWERTYASDFGHHJKLZXCVBNMASDFGHJTYUIOPGHJKLZXCVBNMQAZWSX",
    "TYUIOPGHJKLZXCVBNMQAZWSXEDCRFVTGBYHNUJMIKOLPMJNHYGBVFTCDEXSW",
    
    -- FAKE BASE64 (CLEANED)
    "aGVsbG93b3JsZHRoaXNhaXNmZmFrZQ",
    "Y2hhdGdwdGR3cm90ZXN0YWNrb3Zlcg",
    "dGhpc2FpcxNzdXBlcmxvbmdmZmFrZQ",
    "eW91dGhpbmtdGhpc2FpcxNzb21l",
    "d2h5YXJleW91ZXZlbnjyZWFkaW5n",
    
    -- SHORT PATTERNS
    "var_a",
    "var_b",
    "tmp_x",
    "tmp_y",
    "val_1",
    "val_2",
    "ref_a",
    "ref_b",
    "obj_x",
    "obj_y",
    "func_a",
    "func_b",
    "data_x",
    "data_y",
    "ptr_a",
    "ptr_b",
}

local function generateName(id, scope)
    local name = {};
    local d = id % #varNames
	id = (id - d) / #varNames
	table.insert(name, varNames[d + 1]);
	while id > 0 do
		local d = id % #varNames
		id = (id - d) / #varNames
		table.insert(name, varNames[d + 1]);
	end
	return table.concat(name, "_");
end

local function prepare(ast)
    util.shuffle(varNames);
end

return {
	generateName = generateName, 
	prepare = prepare
};
